
name: Create Azure Resources

on: 
  push:
    paths: 
      - 'ARM/**'
      - '.github/workflows/infraworkflow.yml'
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Standard permission for accessing the repository content

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}    # set this to your Azure Subscription Id
  AZURE_RESOURCEGROUP_NAME: myappresourcegroup                    # set this to your preferred resource group name
  AZURE_WEBAPP_NAME: mywebapp2            # set this to your preferred web app name
  ASP_NAME: webappSP
  SQLSERVER_NAME: demo-webappsql-gh-actions-srvhuz3                  # set this to your preferred sql server name
  DATABASE_NAME: demo-webappsql-gh-actions-dbhuz3                    # set this to your preferred sql database name
  SQLADMIN_LOGIN: ${{ secrets.SQLADMIN_LOGIN }}                  # Create a secret in your GitHub repo for the SQL Admin login name you want to use
  SQLADMIN_PASS: ${{ secrets.SQLADMIN_PASS }}                    # Create a secret in your GitHub repo for the SQL Admin password you want to use

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      
      # Azure login with Federated Identity
      - name: Azure Login with Federated Identity
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: repo
          
      # Deployment of template for resource group    
      - name: Deploy ARM Template resourcegroup
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          region: centralus # Set this to your target region
          template: repo/templates/azuredeploy.resourcegroup.json  # Set this to the location of your template file
          parameters: repo/templates/azuredeploy.resourcegroup.parameters.json rgName=${{env.AZURE_RESOURCEGROUP_NAME}} #override rgName in parameters file

      # Deployment of template for resources    
      - name: Deploy ARM Template resources
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{env.AZURE_RESOURCEGROUP_NAME}}
          region: centralus # Set this to your target region
          template: repo/templates/azuredeploy.json  # Set this to the location of your template file
          parameters: repo/templates/azuredeploy.parameters.json webappName=${{env.AZURE_WEBAPP_NAME}} aspName=${{env.ASP_NAME}} sqlServerName=${{env.SQLSERVER_NAME}} databaseName=${{env.DATABASE_NAME}} sqlAdminLogin=${{env.SQLADMIN_LOGIN}} sqlAdminPass=${{env.SQLADMIN_PASS}} # Set this to the location of your parameters file
